#!/usr/bin/env python3
"""
A string is simply an ordered collection of symbols selected from some alphabet and formed into a word; the length of a string is the number of symbols that it contains.
An example of a length 21 DNA string (whose alphabet contains the symbols 'A', 'C', 'G', and 'T') is "ATGCTTCAGAAAGGTCTTACG."
Given: A DNA string of length at most 1000 nt.
Return: Four integers (separated by spaces) counting the respective number of times that the symbols 'A', 'C', 'G', and 'T' occur in s.
"""

# Dataset
s = "TACCGTCGTTGGTTTTCGTCGAGTTAAACGAGGCTAGAACCTTAAACGCCCGCAATTATTAATAACGTGATCCATATAAGGATATGAATAACCCACGACTACATACGACAGTGTCGCCGGTTGCCATCGTAATGGCGGGGTATTAATGTTAGCTCCCAACGCGTTGGGGCAGTCAGGAAGTATGCCCACTCGACCCGTACCGGCAACAGAGGTGATCGATGAATAGCAGTTTTTTGGATCCCTGGGCCAATACTTTCCGTGTTCAAGCTCTCATGTGAACGATATGTACACCCCGTCACCGTCGGTCGACGCCTTGCGCAGTTTTAAAGGGACGATCATGTTAGACCAGATCAATCTCACGGATTTATCACATAGCAGGGTAACCCATCACAGCTACTATATCGAGGAGGCTAAGTTGATTATCACATCTCGGCAGGCCGCACTCACTCTAATACGTCCGGTTAGCCCCGGCTTCACCTGGACAGATCCGAGGTGGAGGTCGATACTAGGCTACCCCAACCGATGGACCTTTTGGATCTACGCGTGTACGGGGGTCGGATTTTCACCGTTGGAAAAGCCCGACAACAAAGTTCAACTCAGTACTCTGTGATAAAGAACGCGGGACGATCGTAGAATTTTTTCGGGTAATTTCTGCGTTACTAACGTTGGCCATGTAGGATCTTAGCCTAAATGCGCCGCCTAATCCACGGTGTACTCGACGTAATTTCGTCCACACCCTATCGCCGAGCCGTCAATGTACTGACGAGAATCCTAGTCGGGCTGCCGGCCTTTTCCATCGTCATCGTTCTGCTCCGGTGTAGCTGATCCGGACATGCTGTGGGCTGGTTGCCTAGATCTAGTCTGACGGAGATTGTCGCGACGGTATAACCCTTTAAGCCACAATGCCCTATTCTTGATGGGCTATCCGGGTATCGTTGGGTGGTTTGAG"

with open('rosalind_dna.txt', 'r') as fhand:
    dna = fhand.read().replace('\n', '')

print(dna)
out = {'A':0,'C':0, 'G':0, 'T':0}

for nuc in s:
    #print(nuc)
    out[nuc] += 1

print("{} {} {} {}".format(out['A'], out['C'], out['G'], out['T']))

